apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-backend
  namespace: backend
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "500Mi"
    limits.cpu: "500m"
    limits.memory: "500Mi"