apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: backend
spec:
  containers:
  - name: mysql-container
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password123
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_USER
      value: wordpress
    - name: MYSQL_PASSWORD 
      value: password123
    ports:
      - containerPort: 3306
        protocol: TCP
    resources:                            # NOTE: added to satisfy your ResourceQuota
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"