apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1 # Desired Number of Pods
  selector:   # Label Selector for ReplicationController
    app: nginx #
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
